INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("tables", "home", 100, 10);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("refrigerators", "home", 500, 5);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("lawn-mowers", "garden", 300, 6);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("tvs", "electronics", 800, 40);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("blenders", "kitchen", 40, 9);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("sweaters", "clothing", 35, 15);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("toasters", "kitchen", 35, 12);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("ipads", "electronics", 400, 30);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("juice", "food", 12, 100);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("paper towels", "home", 6, 200);